### ISSUE TITLE
Blog post on Dynamically Changeable logging levels has incorrect syntax and is unclear on logger names

### ISSUE THREAD

**Issue by forsberg** [strimzi/strimzi.github.io#358]
https://strimzi.io/blog/2020/11/10/dynamically-changeable-logging/

# Problem 1

The example on inline logging has incorrect syntax. It claims syntax is:

```yaml
logging:
  type: inline
  loggers:
    kafka.root.logger.level = INFO
```

It really should be:

```yaml
logging:
  type: inline
  loggers:
    kafka.root.logger.level: INFO
```

# Problem 2

It really would help us non-Java-Gurus if it was made clear that at least in some parts of the code, the names of the loggers are not obvious. For example, in order for me to enable TRACE logging in a Kafka Connect plugin (Confluent's S3 writer), I had to add the `log4j.logger` prefix, i.e like this:

```yaml
  logging:
    loggers:
      log4j.logger.io.confluent.connect.avro.AvroConverter: TRACE
      log4j.logger.io.confluent.connect.s3.TopicPartitionWriter: TRACE
      log4j.logger.io.confluent.kafka.schemaregistry.avro.AvroSchema: TRACE
      log4j.logger.io.confluent.kafka.schemaregistry.avro.AvroSchemaProvider: TRACE
```

Don't know for what kinds of loggers/plugins etc this is true. May also be Strimzi version dependent, I'm on Strimzi 0.27.1.

# General Observation

Overall, the Strimzi docs are excellent!  Keep it coming!

I have:

* [X] Checked that the problem is not about the Strimzi documentation.
  Documentation issues (those with URLs starting https://strimzi.io/docs/...) should be reported [here](https://github.com/strimzi/strimzi-kafka-operator/issues/new?title=Docs:&labels=documentation).
* [X] Included the URL of the page my issue is about
* [X] Described what I did see and what I was expecting to see
* [X] Added some well-deserved praise to get attention to my issue.
